version: '3'

services:
  frontend:
    image: front-end:latest
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8080:8080"

  backend:
    image: back-end:latest
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mongo:latest
    ports: 
      - 27017:27017


# version: '3'

# services:
#   frontend:
#     image: front-end:latest
#     build:
#       context: ./src
#       dockerfile: Dockerfile
#     ports:
#       - "8080:8080"
#     volumes:
#       - ./src:/app/src # For hot-reloading during development

#   backend:
#     image: back-end:latest
#     build:
#       context: ./server
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./server:/app/server # For hot-reloading during development

#   database:
#     image: mongo:latest
#     ports: 
#       - 27017:27017